src/PecheBooking/Areas/Admin/Controllers/EventsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PecheBooking.Areas.Admin.Models;
using PecheBooking.Data;

namespace PecheBooking.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class EventsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EventsController(ApplicationDbContext context)
        {
            _context = context;
        }

        //
        // GET: /Events/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id, Description, EndDate, StartDate")] ApplicationEvent applicationEvent)
        {
            if (ModelState.IsValid)
            {
                if (applicationEvent.StartDate > applicationEvent.EndDate)
                {
                    ModelState.AddModelError(string.Empty, "La période est incorrect.");
                    return View(applicationEvent);
                }
                _context.Add(applicationEvent);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Reservations", new { Message = ReservationsController.ReservationMessageId.EventCreate });
            }
            return View(applicationEvent);
        }

        //
        // GET /Events/Edit/1
        [HttpGet]        
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var model = await _context.Events.SingleOrDefaultAsync(r => r.Id == id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        //
        // POST : /Events/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id, Description, EndDate, StartDate")] ApplicationEvent applicationEvent)
        {
            if (id != applicationEvent.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (applicationEvent.StartDate > applicationEvent.EndDate)
                {
                    ModelState.AddModelError(string.Empty, "La période est incorrect.");
                    return View(applicationEvent);
                }
                try
                {
                    _context.Update(applicationEvent);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApplicationEventExists(applicationEvent.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return RedirectToAction("Index", "Reservations", new { Message = ReservationsController.ReservationMessageId.EventEdit });
        }

        //
        // GET : /Events/Delete/1
        [HttpGet]        
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationEvent = await _context.Events.SingleOrDefaultAsync(m => m.Id == id);
            if (applicationEvent == null)
            {
                return NotFound();
            }
            return View(applicationEvent);
        }

        //
        // POST : //Events/Delete/1
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            var applicationEvent = await _context.Events.SingleOrDefaultAsync(m => m.Id == id);
            _context.Events.Remove(applicationEvent);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Reservations", new { Message = ReservationsController.ReservationMessageId.EventDelete });
        }

        private bool ApplicationEventExists(int id)
        {
            return _context.Events.Any(e => e.Id == id);
        }
    }
}

src/PecheBooking/Areas/Admin/Controllers/ReservationsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PecheBooking.Areas.Admin.Models;
using PecheBooking.Data;

namespace PecheBooking.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class ReservationsController : Controller
    {
        public ApplicationDbContext _context { get; set; }

        public ReservationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        //
        // GET /Reservation/Index
        [HttpGet]
        public IActionResult Index(ReservationMessageId? message = null)
        {
            ViewData["StatusMessage"] =
                message == ReservationMessageId.EventCreate ? "L'événement a été crée avec succés."
                : message == ReservationMessageId.EventEdit ? "L'événement a été modifié avec succés."
                : message == ReservationMessageId.EventDelete ? "L'événement a été supprimé avec succés."
                : message == ReservationMessageId.ReservationEdit ? "La réservation a été modifié avec succés."
                : message == ReservationMessageId.ReservationDelete ? "La réservation a été supprimé avec succés."
                : "";

            var Reservations = _context.Reservations
                                    .Include(r => r.ReservationInfos)
                                    .ToList()
                                    .Select(r => new {
                                        id = r.Id,
                                        title = r.FirstName + " " + r.LastName + " P:" + r.ReservationInfos[0].Slot,
                                        start = r.ReservationInfos.First().Date,
                                        end = r.ReservationInfos.Last().Date.AddDays(1),
                                        url = string.Format("/Admin/Reservations/Edit/{0}", r.Id),
                                        color = "#FF0000",
                                        allDay = true })
                                    .Where(r => r.end >= DateTime.Today);

            var Events = _context.Events
                                    .Select(r => new {
                                        id = r.Id,
                                        title = r.Description,
                                        start = r.StartDate,
                                        end = r.EndDate.AddDays(1),
                                        url = string.Format("/Admin/Events/Edit/{0}", r.Id),
                                        color = "#FFA500",
                                        allDay = true})
                                    .Where(r => r.end >= DateTime.Today);

            return View(Reservations.Union(Events));
        }

        //
        // GET /Reservation/Edit/1
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var model = await _context.Reservations.Include(r => r.ReservationInfos).SingleOrDefaultAsync(r => r.Id == id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        //
        // POST : /Reservation/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(
            int id, 
            [Bind("Id, IPAdress, FirstName, LastName, PhoneNumber, ReservationInfos")] ApplicationReservation applicationReservation, 
            [FromForm] DateTime start,
            [FromForm] DateTime end,
            [FromForm] int slot)
        {
            if (id != applicationReservation.Id)
            {
                return NotFound();
            }
            if (start > end)
            {
                ModelState.AddModelError(string.Empty, "La période est incorrect.");
                return View(applicationReservation);
            }
            try
            {
                if (applicationReservation.ReservationInfos.First().Date != start || 
                    applicationReservation.ReservationInfos.Last().Date != end)
                {
                    _context.ReservationInfos.RemoveRange(applicationReservation.ReservationInfos);
                    for(var date = start; date <= end; date = date.AddDays(1))
                    {
                        applicationReservation.ReservationInfos.Add(new ApplicationReservationInfo() {
                            Date = date,
                            Slot = slot
                        });
                    }
                }
                if (applicationReservation.ReservationInfos.First().Slot != slot)
                {
                    foreach (var item in applicationReservation.ReservationInfos)
                    {
                        item.Slot = slot;
                    }                    
                }
                _context.Update(applicationReservation);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ApplicationReservationExists(applicationReservation.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("Index", new { Message = ReservationMessageId.ReservationEdit });
        }

        //
        // GET : /Reservation/Delete/1
        [HttpGet]        
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationReservation = await _context.Reservations.SingleOrDefaultAsync(m => m.Id == id);
            if (applicationReservation == null)
            {
                return NotFound();
            }
            return View(applicationReservation);
        }

        //
        // POST : //Events/Delete/1
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            var applicationReservation = await _context.Reservations.Include(r => r.ReservationInfos).SingleOrDefaultAsync(m => m.Id == id);
            _context.ReservationInfos.RemoveRange(applicationReservation.ReservationInfos);
            _context.Reservations.Remove(applicationReservation);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { Message = ReservationMessageId.ReservationDelete });
        }

        private bool ApplicationReservationExists(int id)
        {
            return _context.Reservations.Any(e => e.Id == id);
        }

        public enum ReservationMessageId
        {
            EventCreate,
            EventEdit,
            EventDelete,
            ReservationEdit,
            ReservationDelete
        }
    }
}

src/PecheBooking/Areas/Admin/Views/Reservations/Delete.cshtml
@model ApplicationReservation
@{
    ViewData["Title"] = "Supprimer une réservation";
}

<!-- page content -->
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>@ViewData["Title"]</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="form-group">
                        <label asp-for="FirstName" class="col-md-2 control-label"></label>
                        <input asp-for="FirstName" readonly class="form-control" />
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName" class="col-md-2 control-label"></label>
                        <input asp-for="LastName" readonly class="form-control" />
                    </div>

                    <form class="form-horizontal form-label-left" asp-action="Delete">
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <h2>Êtes vous sur de votre choix ?</h2>
                                <input type="submit" value="Supprimer" class="btn btn-danger" />
                                <a class="btn btn-default" asp-action="Index">Annuler</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

src/PecheBooking/Areas/Admin/Views/Reservations/Edit.cshtml
@model ApplicationReservation
@{
    ViewData["Title"] = "Editer la réservation";
}

<!-- page content -->
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>@ViewData["Title"]</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <form class="form-horizontal form-label-left" asp-action="Edit" method="post">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <input type="hidden" asp-for="Id" readonly class="form-control" />

                        <div class="form-group">
                            <label asp-for="FirstName" class="col-md-2 control-label"></label>
                            <div class="col-md-10">
                                <input asp-for="FirstName" class="form-control" />
                                <span asp-validation-for="FirstName" class="text-danger" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="LastName" class="col-md-2 control-label"></label>
                            <div class="col-md-10">
                                <input asp-for="LastName" class="form-control" />
                                <span asp-validation-for="LastName" class="text-danger" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="PhoneNumber" class="col-md-2 control-label"></label>
                            <div class="col-md-10">
                                <input asp-for="PhoneNumber" class="form-control" />
                                <span asp-validation-for="PhoneNumber" class="text-danger" />
                            </div>
                        </div>

                        <hr />

                        <div class="form-group">
                            <label asp-for="IPAdress" class="col-md-2 control-label"></label>
                            <div class="col-md-10">
                                <input asp-for="IPAdress" readonly class="form-control" />
                            </div>
                        </div>

                        <hr>

                        <div class="form-group">
                            <label asp-for="@Model.ReservationInfos.First().Slot" class="col-md-2 control-label"></label>
                            <div class="col-md-10">
                                @if (Model.ReservationInfos.Count() > 0)
                                {
                                <input name="slot" asp-for="@Model.ReservationInfos.First().Slot" required class="form-control" />
                                }
                                else
                                {
                                <input name="slot" required class="form-control" />
                                }
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label">Début</label>
                            <div class="col-md-10">
                                @if (Model.ReservationInfos.Count() > 0)
                                {
                                <input type="date" name="start" type="date" asp-for="@Model.ReservationInfos.First().Date" required class="form-control" />
                                }
                                else
                                {
                                <input type="date" name="start" required class="form-control" />
                                }
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label">Fin</label>
                            <div class="col-md-10">
                                @if (Model.ReservationInfos.Count() > 0)
                                {
                                <input type="date" name="end" type="date" asp-for="@Model.ReservationInfos.Last().Date" required class="form-control" />
                                }
                                else
                                {
                                <input type="date" name="end" required class="form-control" />
                                }
                            </div>
                        </div>
                    
                        @for (int i = 0; i < Model.ReservationInfos.Count(); i++)
                        {
                            <input type="hidden" asp-for="@Model.ReservationInfos[i].Id" readonly />
                            <input type="hidden" asp-for="@Model.ReservationInfos[i].Date" readonly />
                            <input type="hidden" asp-for="@Model.ReservationInfos[i].Slot" readonly />
                        }

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Sauvegarder" class="btn btn-success" />
                                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model.Id">Supprimer</a>
                                <a class="btn btn-default" asp-action="Index">Annuler</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

src/PecheBooking/Areas/Admin/Views/Reservations/Index.cshtml
@{
    ViewData["Title"] = "Gestion des réservations";
}

<!-- page content -->
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-12 col-xs-12">  
                  
                @if ((string)ViewData["StatusMessage"] != "")
                {
                    <div class="alert alert-success alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                        @ViewData["StatusMessage"]
                    </div>
                }

            <div class="x_panel">
                <div class="x_title">
                    <h2>@ViewData["Title"]</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                        <li><a class="collapse-link" asp-controller="Events" asp-action="Create" data><i class="fa fa-plus"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div id='calendar'></div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
<script>
    $('#calendar').fullCalendar({
        header: {
            left: 'prev,next today',
            center: 'title'
        },
        defaultDate: new Date(),
        navLinks: true,
        editable: false,
        eventLimit: false,
        events: @Html.Raw(JsonConvert.SerializeObject(Model)),
        eventClick: function(calEvent, jsEvent, view) {
            window.location = '/Admin/Reservations/Edit/'+ calEvent.id;
        },
        locale: 'fr'
    });
</script>
}