src/PecheBooking/Areas/Admin/Controllers/MenuController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PecheBooking.Areas.Admin.Models;
using PecheBooking.Data;

namespace PecheBooking.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class MenusController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MenusController(ApplicationDbContext context)
        {
            _context = context;
        }

        //
        // GET /Menu/Index
        [HttpGet]
        public async Task<IActionResult> Index(MenuMessageId? message = null)
        {
            ViewData["StatusMessage"] =
                message == MenuMessageId.Create ? "Le menu a été crée avec succés."
                : message == MenuMessageId.Edit ? "Le menu a été modifié avec succés."
                : message == MenuMessageId.Delete ? "Le menu a été supprimé avec succés."
                : "";    
            return View(await _context.Menus.OrderBy(r => r.MenuText).ToListAsync());
        }

        //
        // GET: /Menu/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Menu/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id, MenuText, LinkUrl")] ApplicationMenu applicationMenu)
        {
            if (ModelState.IsValid)
            {
                _context.Add(applicationMenu);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { Message = MenuMessageId.Create });
            }
            return View(applicationMenu);
        }

        //
        // GET /Menu/Edit/1
        [HttpGet]        
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var model = await _context.Menus.SingleOrDefaultAsync(r => r.Id == id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        //
        // POST : /Menu/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id, MenuText, LinkUrl")] ApplicationMenu applicationMenu)
        {
            if (id != applicationMenu.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(applicationMenu);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApplicationMenuExists(applicationMenu.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return RedirectToAction("Index", new { Message = MenuMessageId.Edit });
        }

        //
        // GET : /Menu/Delete/1
        [HttpGet]        
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationMenu = await _context.Menus.SingleOrDefaultAsync(m => m.Id == id);
            if (applicationMenu == null)
            {
                return NotFound();
            }
            return View(applicationMenu);
        }

        //
        // POST : //Menu/Delete/1
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            var applicationMenu = await _context.Menus.SingleOrDefaultAsync(m => m.Id == id);
            _context.Menus.Remove(applicationMenu);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { Message = MenuMessageId.Delete });
        }

        private bool ApplicationMenuExists(int id)
        {
            return _context.Menus.Any(e => e.Id == id);
        }

        public enum MenuMessageId
        {
            Create,
            Edit,
            Delete
        }
    }
}

src/PecheBooking/Areas/Admin/Views/Menus/Create.cshtml
@model ApplicationMenu
@{
    ViewData["Title"] = "Crée un lien";
}

<!-- page content -->
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>@ViewData["Title"]</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <form class="form-horizontal form-label-left" asp-controller="Menus" asp-action="Create" method="post">
                        <hr />
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="MenuText" class="col-md-2 control-label"></label>
                            <div class="col-md-10">
                                <input asp-for="MenuText" class="form-control" />
                                <span asp-validation-for="MenuText" class="text-danger" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="LinkUrl" class="col-md-2 control-label"></label>
                            <div class="col-md-10">
                                <input asp-for="LinkUrl" class="form-control" />
                                <span asp-validation-for="LinkUrl" class="text-danger" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Ajouter" class="btn btn-success" />
                                <a class="btn btn-default" asp-action="Index">Annuler</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

src/PecheBooking/Areas/Admin/Views/Menus/Delete.cshtml
@model ApplicationMenu
@{
    ViewData["Title"] = "Supprimer un lien";
}

<!-- page content -->
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>@ViewData["Title"]</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    
                    <div class="form-group">
                        <label asp-for="MenuText" class="col-md-2 control-label"></label>
                        <div class="col-md-10">
                            <input asp-for="MenuText" readonly class="form-control" />
                        </div>
                    </div>

                    <form class="form-horizontal form-label-left" asp-action="Delete">
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <h2>Êtes vous sur de votre choix ?</h2>
                                <input type="submit" value="Supprimer" class="btn btn-danger" />
                                <a class="btn btn-default" asp-action="Index">Annuler</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

src/PecheBooking/Areas/Admin/Views/Menus/Edit.cshtml
@model ApplicationMenu
@{
    ViewData["Title"] = "Editer un lien";
}

<!-- page content -->
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>@ViewData["Title"]</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <form class="form-horizontal form-label-left" asp-controller="Menus" asp-action="Edit" method="post">
                        <hr />
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Id" class="col-md-2 control-label"></label>
                            <div class="col-md-10">
                                <input asp-for="Id" readonly class="form-control" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="MenuText" class="col-md-2 control-label"></label>
                            <div class="col-md-10">
                                <input asp-for="MenuText" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="LinkUrl" class="col-md-2 control-label"></label>
                            <div class="col-md-10">
                                <input asp-for="LinkUrl" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Sauvegarder" class="btn btn-success" />
                                <a class="btn btn-default" asp-action="Index">Annuler</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

src/PecheBooking/Areas/Admin/Views/Menus/Index.cshtml
@model IEnumerable<ApplicationMenu>
@{
    ViewData["Title"] = "Gestion du menu";
}

<!-- page content -->
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-12 col-xs-12">
            
            @if ((string)ViewData["StatusMessage"] != "")
            {
                <div class="alert alert-success alert-dismissible fade in" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                    @ViewData["StatusMessage"]
                </div>
            }

            <div class="x_panel">
                <div class="x_title">
                    <h2>@ViewData["Title"]</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                        <li><a class="collapse-link" asp-action="Create" data><i class="fa fa-plus"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table class="table">
                        <thead>
                            <tr>
                            <th> </th>
                            <th>
                                @Html.DisplayNameFor(model => model.MenuText)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.LinkUrl)
                            </th>
                        </thead>
                        <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td class="col-md-1">
                                <ul class="nav navbar-right panel_toolbox">
                                    <li><a asp-action="Edit" asp-route-id="@item.Id"><i class="fa fa-pencil"></i></a></li>
                                    <li><a asp-action="Delete" asp-route-id="@item.Id"><i class="fa fa-remove"></i></a></li>
                                </ul>
                            </td>
                            <td class="col-md-2">
                                @Html.DisplayFor(modelItem => item.MenuText)
                            </td>
                            <td class="col-md-10">
                                @Html.DisplayFor(modelItem => item.LinkUrl)
                            </td>
                        </tr>
                        }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>