src/PecheBooking/Controllers/ReserveController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PecheBooking.Areas.Admin.Models;
using PecheBooking.Data;
using PecheBooking.ViewModels.ReserveViewModels;

namespace PecheBooking.Controllers
{
    public class ReserveController : Controller
    {
        public CultureInfo Culture { get; set; }
        public ApplicationDbContext Context { get; set; }

        public ReserveController(ApplicationDbContext context)
        {
            Context = context;
            Culture = CultureInfo.CurrentCulture;
        }
        
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(InformationViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = Context.Reservations.Add(new ApplicationReservation {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    PhoneNumber = model.PhoneNumber,
                    IPAdress = HttpContext.Connection.RemoteIpAddress?.ToString(),
                    ReservationInfos = new List<ApplicationReservationInfo>()
                });
                for(var date = model.Start.Value; date <= model.End; date = date.AddDays(1))
                {
                    result.Entity.ReservationInfos.Add(new ApplicationReservationInfo() {
                        Date = date,
                        Slot = model.Slot
                    });
                }
                await Context.SaveChangesAsync();
                return RedirectToAction("ReservationConfirm", model);
            }
            return View(model);
        }
        
        [HttpGet]
        public IActionResult ReservationConfirm(InformationViewModel model)
        {
            if (ModelState.IsValid)
            {
                return View(model);
            }
            return RedirectToAction("Index");
        }

        public IActionResult DateValidation(DateTime Start, DateTime End)
        {
            var Today = DateTime.Today;
            var StartWeek = Culture.Calendar.GetWeekOfYear(Start, CalendarWeekRule.FirstFourDayWeek, DayOfWeek.Monday);
            var EndWeek = Culture.Calendar.GetWeekOfYear(End, CalendarWeekRule.FirstFourDayWeek, DayOfWeek.Monday);
            //
            var test = Start.Subtract(End).TotalDays;
            if (Start.Subtract(Today).TotalDays < 0)
            {
                return Json("La période de réservation est expiré.");
            }
            else if (Start.Ticks > End.Ticks)
            {
                return Json("La période de réservation est incorrect.");
            }
            else if (End.Subtract(Start).TotalDays > 3)
            {
                return Json("La réservation ne peut excellé 3 jours consécutifs.");
            }
            else if (Today.Subtract(Start).TotalDays > 30 || Today.Subtract(End).TotalDays > 30)
            {
                return Json("La réservation ne peut être pris plus de 30 jours à l'avance.");
            }
            else if (StartWeek != EndWeek)
            {
                return Json("La réservation ne peut être pris sur deux semaines à la fois.");
            }
            else if (Context.Events.Any(r => r.StartDate >= Start && r.StartDate <= End && r.EndDate <= End))
            {
                return Json("La réservation ne peut contenir un jour d'évévement.");
            }
            else if (Context.ReservationInfos
                        .GroupBy(r => r.Date)
                        .Where(r => r.Count() >= 2)
                        .Where(r => r.Key >= Start && r.Key <= End)
                        .Any())
            {
                return Json("La réservation ne peut contenir un jour complet.");
            }
            return Json(true);
        }

        public IActionResult SlotValidation(DateTime Start, DateTime End, int Slot)
        {
            var Week = Culture.Calendar.GetWeekOfYear(Start, CalendarWeekRule.FirstFourDayWeek, DayOfWeek.Monday);
            var WeekPair = ((Week % 2) == 0);
            var SlotPair = ((Slot % 2) == 0);
            if (SlotPair != WeekPair)
            {
                if (WeekPair)
                    return Json("Veuillez selectionner un poste paire.");
                else
                    return Json("Veuillez selectionner un poste impaire.");
            }
            if (Context.ReservationInfos.Count(r => r.Date >= Start && r.Date <= End && r.Slot == Slot) > 0)
            {
                return Json("Ce poste est déjà réservé durant cette période.");
            }
            return Json(true);
        }
    }
}

src/PecheBooking/Views/Reserve/Index.cshtml
@model InformationViewModel
@{
    ViewData["Title"] = "Prendre une réservation";
}
@section Css {
    <link href="~/css/glDatePicker.default.css" rel="stylesheet" type="text/css">
    <link href="~/css/glDatePicker.darkneon.css" rel="stylesheet" type="text/css">
}

<!-- boostrap-icons -->
<div class="contact">
    <div class="container">
        <div class="why-choose-grids ">
            <div class="col-md-12 why-choose-grid">
                <div class="why-choose-grid-hover">
					<p>@ViewData["Title"]</p>
				</div>
                <div class="why-choose-grds" style="background:white">
                    <div class="col-xs-5 why-choose-grd">
                        <img src="/images/plan.jpg" alt=" " class="img-responsive">
                    </div>
                    <div class="col-xs-7 why-choose-grd-right">
                        <form id="form" asp-controller="Reserve" asp-action="Index">

                            <h4>Choisissez la période</h4>

                            <div class="row">
                                <div class="col-md-12">
                                    <span asp-validation-for="Start" class="text-danger errors"></span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <span asp-validation-for="End" class="text-danger errors"></span>
                                </div>
                            </div>                       
                            <div class="row">
                                <div class="col-md-5 form-group">
                                    <input id="datepicker1" readonly asp-for="Start" gldp-id="start" class="form-control" placeholder="Date de début" aria-describedby="alert alert-danger">
                                    <div gldp-el="start" style="width: 239px; height: 300px;position:absolute; z-index:50">                        
                                    </div>
                                </div>
                                <div class="col-md-5 form-group">
                                    <input id="datepicker2" readonly asp-for="End" gldp-id="end" class="form-control" placeholder="Date de fin" aria-describedby="alert alert-danger">
                                    <div gldp-el="end" style="width: 239px; height: 300px;position:absolute; z-index:50">                        
                                    </div>                                         
                                </div>
                            </div>

                            <h4>Choisissez le poste</h4>

                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-12">
                                        <span asp-validation-for="Slot" class="text-danger"></span>
                                    </div>
                                    <div class="col-md-6">
                                        <select id="slot" asp-for="Slot" class="form-control" >
                                            <option value="1" class="select2-container--disabled">Poste 1</option>
                                            <option value="2">Poste 2</option>
                                            <option value="3">Poste 3</option>
                                            <option value="4">Poste 4</option>
                                            <option value="5">Poste 5</option>
                                            <option value="6">Poste 6</option>
                                            <option value="7">Poste 7</option>
                                            <option value="8">Poste 8</option>
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <h4>Information personnelle</h4>

                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-12">
                                        <span asp-validation-for="FirstName" class="text-danger"></span>
                                    </div>
                                    <div class="col-md-6">
                                        <input asp-for="FirstName" class="form-control" placeholder="Prénom">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-12">
                                        <span asp-validation-for="LastName" class="text-danger"></span>
                                    </div>
                                    <div class="col-md-6">
                                        <input asp-for="LastName" class="form-control" placeholder="Nom">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-12">
                                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                                    </div>
                                    <div class="col-md-6">
                                        <input asp-for="PhoneNumber" class="form-control" placeholder="Téléphone">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-success submit">Envoyer</button>
                            </div>
                        </form>
					</div>
                    <div class="clearfix"> </div>
                </div>
            </div>
        </div>
         <div class="clearfix"> </div>
    </div>
</div>
<!-- //boostrap-icons -->

@section Scripts {    
    
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }

    <environment names="Development">
        <script src="~/js/glDatePicker.js"> </script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/js/glDatePicker.min.js"> </script>
    </environment>

    <!-- API Event -->
    <script type="text/javascript">
        var events = null;
        $.ajax({
            async: false,
            type: "GET",
            url: '/api/Event',
            success: function(data) 
            {
                events = data;
            }
        });
    </script>
    <!-- API Reservation -->
    <script type="text/javascript">
        var reservations = null;
        $.ajax({
            async: false,
            type: "GET",
            url: '/api/Reservation',
            success: function(data)
            {
                reservations = data;
            }
        });
    </script>
    <!-- Datepicker -->
    <script type="text/javascript">
        var MinDate = new Date();
        var MaxDate = new Date(); 
        MaxDate = new Date(MaxDate.setDate(MaxDate.getDate() + 30));

        $('#datepicker1, #datepicker2').glDatePicker({
            allowYearSelect: false,
            allowMonthSelect: false,
            cssName: 'darkneon',
            dowOffset: 1,
            fullDates: reservations,
            specialDates: events,
            selectableDateRange: [{ from: MinDate, to: MaxDate }],
            onClick: function(target, cell, date, data) 
            {
                if(data != null)
                {
                    if (data.message){
                        alert(data.message);
                    } else {
                        alert("Plus de place.");
                    }
                }
                else
                {
                    target.val(date.getFullYear() + '-' + (date.getMonth() + 1) + '-' + date.getDate());
                    onChange();
                }
            }
        });
    </script>
    <!-- GetWeek -->
    <script type="text/javascript">
        Date.prototype.getWeek = function()
        {            
            var tdt = new Date(this.valueOf());
            var dayn = (this.getDay() + 6) % 7;
            tdt.setDate(tdt.getDate() - dayn + 3);
            var firstThursday = tdt.valueOf();
            tdt.setMonth(0, 1);
            if (tdt.getDay() !== 4) 
            {
                tdt.setMonth(0, 1 + ((4 - tdt.getDay()) + 7) % 7);
            }
            return 1 + Math.ceil((firstThursday - tdt) / 604800000);
        };
    </script>
    <!-- Change datepicker - Available slot -->
    <script type="text/javascript">
        function onChange()
        { 
            var usedSlot = [];
            var select = document.getElementById('slot');
            var Start = new Date(Date.parse(document.getElementById('datepicker1').value));
            var End = new Date(Date.parse(document.getElementById('datepicker2').value));
            var pair = (Start.getWeek() % 2 == 0)

            if (!isNaN(Start) && !isNaN(End))
            {
                $.ajax({
                    async: false,
                    data: {
                        start: Start.getFullYear() + "-" + (Start.getMonth() + 1) + "-" + Start.getDate(),
                        end: End.getFullYear() + "-" + (End.getMonth() + 1) + "-" + End.getDate()
                    },
                    type: "GET",
                    url: "/api/Slot",
                    success: function(data)
                    {
                        usedSlot = data;
                    }
                });
            }
            for(i = 0; i < 8; i++) 
            {
                if (pair == 1) {
                    select.options[i].disabled = ((i % 2) == 0) ? true : false
                    select.options[i].style.color = ((i % 2) == 0) ? "orange" : "green"
                } else {
                    select.options[i].disabled = ((i % 2) != 0) ? true : false
                    select.options[i].style.color = ((i % 2) != 0) ? "orange" : "green"
                }
                if (usedSlot.indexOf(i+1) != -1) {
                    select.options[i].disabled = true
                    select.options[i].style.color = "red"
                }
            }
        };
    </script>
    <!-- Load page -->
    <script type="text/javascript">
        onChange();
    </script>
    <!-- Validation -->
    <script type="text/javascript">
        $("#datepicker1, #datepicker2, #slot").blur(function () 
        {
            $('#datepicker1').valid();
            $('#datepicker2').valid();
        });
    </script>
}

src/PecheBooking/Views/Reserve/ReservationConfirm.cshtml
@model InformationViewModel
@using System.Globalization;
@{
    ViewData["Title"] = "Réservation enregistrée";
}

<div class="contact">
    <div class="container">
        <div class="why-choose-grids ">
            <div class="col-md-12 why-choose-grid">
                <div class="why-choose-grid-hover">
					<p>@ViewData["Title"]</p>
				</div>
                <div class="why-choose-grds" style="background:white">
                    <div class="col-xs-5 why-choose-grd">
                        <img src="/images/partner.jpg" alt=" " class="img-responsive">
                    </div>
                    <div class="col-xs-7 why-choose-grd-right">
                        <p>Votre réservation a bien été enregistré.</p>

                        <hr>

                        <h4>Resumé de réservation</h4>
                        <p><strong>Poste</strong> : @Model.Slot</p>
                        @if (Model.Start.Value != Model.End.Value)
                        {
                            <p><strong>Période</strong> : du @Model.Start.Value.ToString("M") au @Model.End.Value.ToString("D")</p>
                        }
                        else
                        {
                            <p><strong>Journée du</strong> : @Model.Start.Value.ToString("D")</p>
                        }

                        <hr>

                        <p>En cas de problème ou si vous souhaitez modifier votre réservation, merci de prendre contact à un des numéros suivants :</p>
                        <p>Monsieur Julien CLEMENT: Tel: 06.37.10.61.34</p>
                        <p>Monsieur John BORDIER : Tel: 06.23.89.32.92</p>
					</div>
                    <div class="clearfix"> </div>
                </div>
            </div>
        </div>
         <div class="clearfix"> </div>
    </div>
</div>