src/PecheBooking/ViewModels/HomeVIewModels/GalleryViewModel.cs
using System.Collections.Generic;
using PecheBooking.Areas.Admin.Models;

namespace PecheBooking.ViewModels.HomeViewModels
{
    public class GalleryViewModel
    {
        public int Count { get; set; }
        public int Offset { get; set; }
        public int Page { get; set; }
        public int PageCount { get; set; }
        public int Previous { get; set; }
        public int Next { get; set; }
        public int Total { get; set; }
        public List<ApplicationImage> Images { get; set; }
    }
}

src/PecheBooking/Areas/Admin/Controllers/GalleriesController.cs
using System;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PecheBooking.Areas.Admin.Models;
using PecheBooking.Data;

namespace PecheBooking.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class GalleriesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private IHostingEnvironment _environment;

        public GalleriesController(
            ApplicationDbContext context,
            IHostingEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        //
        // GET /Galleries/Index
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Galleries.OrderBy(r => r.Id).ToListAsync());
        }

        //
        // GET : /Galleries/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        //
        // GET : /Galleries/Delete/1
        [HttpGet]        
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationImage = await _context.Galleries.SingleOrDefaultAsync(m => m.Id == id);
            if (applicationImage == null)
            {
                return NotFound();
            }
            return View(applicationImage);
        }

        //
        // POST : //Galleries/Delete/1
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            var applicationImage = await _context.Galleries.SingleOrDefaultAsync(m => m.Id == id);
            _context.Galleries.Remove(applicationImage);
            System.IO.File.Delete(Path.Combine(_environment.WebRootPath, "uploads", applicationImage.Image));
            System.IO.File.Delete(Path.Combine(_environment.WebRootPath, "uploads", applicationImage.ThumbnailImage));
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        //
        // GET /Galleries/Edit/1
        [HttpGet]        
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var model = await _context.Galleries.SingleOrDefaultAsync(r => r.Id == id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        //
        // POST : /Menu/Edit/5
        [HttpPost]
        public async Task<IActionResult> Edit(int id, IFormFile image)
        {
            if (ModelState.IsValid)
            { 
                var applicationImage = await _context.Galleries.SingleOrDefaultAsync(r => r.Id == id);

                if (id != applicationImage.Id)
                {
                    return NotFound();
                }

                if (applicationImage == null)
                {
                    return NotFound();
                }
                if (image == null)
                {
                    return NotFound();
                }
                try
                {
                    applicationImage = await CreateImage(image, applicationImage);
                    if (applicationImage == null)
                    {
                        return BadRequest();
                    }
                    _context.Update(applicationImage);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApplicationImageExists(applicationImage.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return RedirectToAction("Index");
        }

        //
        // GET /Galleries/Upload
        [HttpPost]
        public async Task<JsonResult> Upload(IFormFile file)
        {
            if (ModelState.IsValid)
            {
                var applicationImage = await CreateImage(file, new ApplicationImage());
                if (applicationImage == null)
                {
                    return Json("Error");
                }
                _context.Add(applicationImage);
                await _context.SaveChangesAsync();

            }
            return Json("Ok");
        }

        #region Helper

        private async Task<ApplicationImage> CreateImage(IFormFile file, ApplicationImage applicationImage)
        {
            try
            {
                var acceptType = new string[] { "image/jpeg", "image/png", "image/bmp" };
                var filename = Path.GetFileNameWithoutExtension(file.FileName);
                var uploads = Path.Combine(_environment.WebRootPath, "uploads");
                var uniqid = Guid.NewGuid().ToString();

                if (!Directory.Exists(uploads))
                {
                    Directory.CreateDirectory(uploads);
                }
                if (!acceptType.Any(r => r == file.ContentType))
                {
                    return null;
                }
                if (file.Length == 0)
                {
                    return null;
                }
                if (applicationImage.Image != null)
                {
                    System.IO.File.Delete(Path.Combine(_environment.WebRootPath, "uploads", applicationImage.Image));
                    System.IO.File.Delete(Path.Combine(_environment.WebRootPath, "uploads", applicationImage.ThumbnailImage));
                }

                applicationImage.Image = file.FileName.Replace(filename, uniqid);
                applicationImage.ThumbnailImage = file.FileName.Replace(filename, uniqid+".thumb");

                using (var fileStream = new FileStream(Path.Combine(uploads, applicationImage.Image), FileMode.CreateNew))
                {
                    await file.CopyToAsync(fileStream);
                }

                Image.FromFile(Path.Combine(uploads, applicationImage.Image))
                    .GetThumbnailImage(250, 180, null, IntPtr.Zero)
                    .Save(Path.Combine(uploads, applicationImage.ThumbnailImage));
            }
            catch (Exception)
            {
                return null;
            }
            return applicationImage;
        }

        #endregion

        private bool ApplicationImageExists(int id)
        {
            return _context.Menus.Any(e => e.Id == id);
        }
    }
}

src/PecheBooking/Areas/Admin/Views/Galleries/Create.cshtml
@{
    ViewData["Title"] = "Ajouter une image";
}

<!-- page content -->
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>@ViewData["Title"]</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <form id="addGalleryForm" class="dropzone dz-clickable" asp-area="Admin" asp-controller="Galleries" asp-action="Upload" method="post">
                        <div class="dz-default dz-message">
                            <span>Glisser les images ici.</span>
                        </div>
                    </form>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <a class="btn btn-default" asp-action="Index">Retour</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/PecheBooking/Areas/Admin/Views/Galleries/Delete.cshtml
@{
    ViewData["Title"] = "Supprimer un lien";
}

<!-- page content -->
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>@ViewData["Title"]</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">                    
                    <div class="row">
                        <div class="col-md-5">
                            <div class="thumbnail">
                                <div class="view view-first">
                                    <img style="width: 100%; height: 100%; display: block;" src="~/uploads/@Model.ThumbnailImage" alt="image">
                                </div>
                            </div>
                        </div>
                    </div>

                    <form class="form-horizontal form-label-left" asp-action="Delete">
                        <div class="form-group">
                            <div class="col-md-12">
                                <h2>Êtes vous sur de votre choix ?</h2>
                                <input type="submit" value="Supprimer" class="btn btn-danger" />
                                <a class="btn btn-default" asp-action="Index">Annuler</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

src/PecheBooking/Areas/Admin/Views/Galleries/Edit.cshtml
@model ApplicationImage
@{
    ViewData["Title"] = "Remplacer l'image";
}

<!-- page content -->
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>@ViewData["Title"]</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="row">
                        <div class="col-md-offset-2 col-md-5">
                            <div class="thumbnail">
                                <div class="view view-first">
                                    <img style="width: 100%; height: 100%; display: block;" src="~/uploads/@Model.ThumbnailImage" alt="image">
                                </div>
                            </div>
                        </div>
                    </div>
                    <form class="form-horizontal form-label-left" asp-controller="Galleries" asp-action="Edit" enctype="multipart/form-data" method="post">
                        <hr />
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <input asp-for="Id" type="hidden" class="form-control" />
                        <div class="form-group">
                            <label class="col-md-2 control-label">Image</label>
                            <div class="col-md-10">
                                <input id="image" name="image" type="file" multiple class="form-control" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Sauvegarder" class="btn btn-success" />
                                <a class="btn btn-default" asp-action="Index">Annuler</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

src/PecheBooking/Areas/Admin/Views/Galleries/Index.cshtml
@model IEnumerable<ApplicationImage>
@{
    ViewData["Title"] = "Gestion de la galerie";
}

<!-- page content -->
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>@ViewData["Title"]</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                        <li><a class="collapse-link" asp-action="Create" data><i class="fa fa-plus"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="row">
                        @foreach (var item in Model)
                        {
                        <div class="col-md-55">
                            <div class="thumbnail">
                                <div class="view view-first">
                                    <img style="width: 100%; display: block;" src="~/uploads/@item.ThumbnailImage" onerror="this.src='/images/undefined.png'" alt="image">
                                    <div class="mask">
                                        <div class="tools tools-bottom">
                                            <a href="~/uploads/@item.Image" target="_blank"><i class="fa fa-search-plus"></i></a>
                                            <a asp-action="Edit" asp-route-id="@item.Id"><i class="fa fa-pencil"></i></a>
                                            <a asp-action="Delete" asp-route-id="@item.Id"><i class="fa fa-remove"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        }
                        @if (Model.Count() == 0)
                        {
                            <p>Aucune image dans la galerie.</p>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>